name: flutter_string_to_rich_text
description: A helper that convert strings to rich text
version: 1.0.0
homepage:
repository: https://github.com/edram/flutter_string_to_rich_text

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  collection: ^1.17.0